package org.example.calendar.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.calendar.dao.persistence.Calendar;
import org.example.calendar.dao.persistence.CalendarExample;

public interface CalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    long countByExample(CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int deleteByExample(CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int insert(Calendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int insertSelective(Calendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    List<Calendar> selectByExample(CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    Calendar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Calendar row, @Param("example") CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Calendar row, @Param("example") CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Calendar row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendars
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Calendar row);
}