package org.example.calendar.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.calendar.dao.persistence.Event;
import org.example.calendar.dao.persistence.EventExample;

public interface EventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    long countByExample(EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int deleteByExample(EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int insert(Event row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int insertSelective(Event row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    List<Event> selectByExampleWithBLOBs(EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    List<Event> selectByExample(EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    Event selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Event row, @Param("example") EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") Event row, @Param("example") EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Event row, @Param("example") EventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Event row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Event row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Event row);
}