package org.example.calendar.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.calendar.dao.persistence.Reminder;
import org.example.calendar.dao.persistence.ReminderExample;

public interface ReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    long countByExample(ReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int deleteByExample(ReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int insert(Reminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int insertSelective(Reminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    List<Reminder> selectByExample(ReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    Reminder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Reminder row, @Param("example") ReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Reminder row, @Param("example") ReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Reminder row);
}