package org.example.calendar.dao.persistence;

import java.io.Serializable;
import java.util.Date;

public class Event implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.calendar_id
     *
     * @mbg.generated
     */
    private Long calendarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.start_datetime
     *
     * @mbg.generated
     */
    private Date startDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.end_datetime
     *
     * @mbg.generated
     */
    private Date endDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.is_all_day
     *
     * @mbg.generated
     */
    private Boolean isAllDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.recurrence_rule
     *
     * @mbg.generated
     */
    private String recurrenceRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.recurrence_end_date
     *
     * @mbg.generated
     */
    private Date recurrenceEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_events.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_events
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.id
     *
     * @return the value of calendar_events.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.id
     *
     * @param id the value for calendar_events.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.calendar_id
     *
     * @return the value of calendar_events.calendar_id
     *
     * @mbg.generated
     */
    public Long getCalendarId() {
        return calendarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.calendar_id
     *
     * @param calendarId the value for calendar_events.calendar_id
     *
     * @mbg.generated
     */
    public void setCalendarId(Long calendarId) {
        this.calendarId = calendarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.title
     *
     * @return the value of calendar_events.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.title
     *
     * @param title the value for calendar_events.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.location
     *
     * @return the value of calendar_events.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.location
     *
     * @param location the value for calendar_events.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.start_datetime
     *
     * @return the value of calendar_events.start_datetime
     *
     * @mbg.generated
     */
    public Date getStartDatetime() {
        return startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.start_datetime
     *
     * @param startDatetime the value for calendar_events.start_datetime
     *
     * @mbg.generated
     */
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.end_datetime
     *
     * @return the value of calendar_events.end_datetime
     *
     * @mbg.generated
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.end_datetime
     *
     * @param endDatetime the value for calendar_events.end_datetime
     *
     * @mbg.generated
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.is_all_day
     *
     * @return the value of calendar_events.is_all_day
     *
     * @mbg.generated
     */
    public Boolean getIsAllDay() {
        return isAllDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.is_all_day
     *
     * @param isAllDay the value for calendar_events.is_all_day
     *
     * @mbg.generated
     */
    public void setIsAllDay(Boolean isAllDay) {
        this.isAllDay = isAllDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.recurrence_rule
     *
     * @return the value of calendar_events.recurrence_rule
     *
     * @mbg.generated
     */
    public String getRecurrenceRule() {
        return recurrenceRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.recurrence_rule
     *
     * @param recurrenceRule the value for calendar_events.recurrence_rule
     *
     * @mbg.generated
     */
    public void setRecurrenceRule(String recurrenceRule) {
        this.recurrenceRule = recurrenceRule == null ? null : recurrenceRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.recurrence_end_date
     *
     * @return the value of calendar_events.recurrence_end_date
     *
     * @mbg.generated
     */
    public Date getRecurrenceEndDate() {
        return recurrenceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.recurrence_end_date
     *
     * @param recurrenceEndDate the value for calendar_events.recurrence_end_date
     *
     * @mbg.generated
     */
    public void setRecurrenceEndDate(Date recurrenceEndDate) {
        this.recurrenceEndDate = recurrenceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.created_by
     *
     * @return the value of calendar_events.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.created_by
     *
     * @param createdBy the value for calendar_events.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.created_at
     *
     * @return the value of calendar_events.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.created_at
     *
     * @param createdAt the value for calendar_events.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.updated_at
     *
     * @return the value of calendar_events.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.updated_at
     *
     * @param updatedAt the value for calendar_events.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_events.description
     *
     * @return the value of calendar_events.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_events.description
     *
     * @param description the value for calendar_events.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}