package org.example.calendar.dao.persistence;

import java.io.Serializable;
import java.util.Date;

public class Reminder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_reminders.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_reminders.event_id
     *
     * @mbg.generated
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_reminders.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_reminders.minutes_before
     *
     * @mbg.generated
     */
    private Integer minutesBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_reminders.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_reminders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_reminders.id
     *
     * @return the value of calendar_reminders.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_reminders.id
     *
     * @param id the value for calendar_reminders.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_reminders.event_id
     *
     * @return the value of calendar_reminders.event_id
     *
     * @mbg.generated
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_reminders.event_id
     *
     * @param eventId the value for calendar_reminders.event_id
     *
     * @mbg.generated
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_reminders.method
     *
     * @return the value of calendar_reminders.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_reminders.method
     *
     * @param method the value for calendar_reminders.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_reminders.minutes_before
     *
     * @return the value of calendar_reminders.minutes_before
     *
     * @mbg.generated
     */
    public Integer getMinutesBefore() {
        return minutesBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_reminders.minutes_before
     *
     * @param minutesBefore the value for calendar_reminders.minutes_before
     *
     * @mbg.generated
     */
    public void setMinutesBefore(Integer minutesBefore) {
        this.minutesBefore = minutesBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_reminders.created_at
     *
     * @return the value of calendar_reminders.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_reminders.created_at
     *
     * @param createdAt the value for calendar_reminders.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}